### ISSUE TITLE
Implement batchtools_config

### ISSUE THREAD

**Issue by mllg** [HenrikBengtsson/future.batchtools#10]
Currently you have to set up the cluster twice:

1. For `batchtools` where you create a configuration file + a template file; the config file calls the cluster function constructor and possibly sets additional cluster-specific options like default resources or the temp directory.
2. For `future.batchtools` where you select the scheduler via `batchtools_[scheduler]` and re-use the template file. `future.batchtools` then calls the appropriate cluster function constructor. Unsure if you can  set additional options via `tweak()`?

A `batchtools_config` plan could just rely on `batchtools` to be configured. In other words, `future.batchtools` could just call `makeRegistry()` and **not** overwrite the cluster functions backend.

**Comment by jakob-r** [comment]
@HenrikBengtsson What is your stance on this? Was about to open the same issue.

For me this it always a nice feature of batchtools that the code was independent of the concrete parallelization technique. Now that `mlr3` relies on `future` it is even more interesting to use batchtools elegantly.

**Comment by jakob-r** [comment]
One could use `batchtools::findConfFile()` and source that into an environment and extract the cluster function from there or you take this workaround:

```r
library(batchtools.future)
library(batchtools)
temp_reg = makeRegistry(file.dir = NA) #just a dummy to get the systems default cluster function
plan(batchtools_custom, cluster.functions = temp_reg$cluster.functions)
```

**Comment by HenrikBengtsson** [comment]
Just for my clarification, the ask here is to make it easier for people who already use 'batchtools' by itself to make use of future.batchtools, correct?  That is, is the problem right now is that you cannot just make use of an existing 'batchtools' setup but have to take extra steps to get that one working in future.batchtools?

For your clarification: it's been many moons since I ran 'batchtools' by itself.

**Comment by HenrikBengtsson** [comment]
I've now updated `batchtools_custom()` such that (a) it no longer requires `cluster.functions` but instead (b) one can specify argument `conf.file` which is passed down to `batchtools::makeRegistry()`.  The default is `conf.file = findConfFile()`.

This way, if a user already has a batcthools configuration file (an R script) set up on the batchtools search path, they can use:
```r
plan(batchtools_custom)
```
to pick that one up.  Is that what you were asking for?

**Comment by jakob-r** [comment]
Yes. It looks right. Do you need more from our side?

**Comment by HenrikBengtsson** [comment]
Thanks. I'll go ahead a prepare the next release/submission to CRAN.  If you wanna give this a serious spin before that's completed, please install:
```r
remotes::install_github("HenrikBengtsson/future.batchtools@develop")
```

**Comment by HenrikBengtsson** [comment]
Wow, 24 minutes from submission to going live.  So, yeah future.batchtools 0.9.0 is already on CRAN
