### ISSUE TITLE
Result of nested {remote} -> {batchtools_slurm} -> {multicore} not distributed back to local machine

### ISSUE THREAD

**Issue by tpilz** [HenrikBengtsson/future.batchtools#38]
Hi Henrik,
thanks for your great package. It works basically fine, I only run into an issue when submitting a multicore job to a cluster and I wonder if I am doing anything wrong or whether this might be related to the HPC I am using.

Consider the following example code I am executing from my local machine:
```
library(future.batchtools) 
library(listenv)

plan(list(tweak(remote, workers = "myaccount@remote.cluster"),
          tweak(batchtools_slurm, resources = list(walltime = 600, ncpus=8)),
          tweak(multicore, workers = 8)
) )

# run at remote
dat_f <- future({
  # job at the cluster
  dat %<-% {
    dat_t <- listenv()
    cores <- availableCores()
    for(f in 1:8) {
      # multicore processes within job
      dat_t[[f]] %<-% {
        Sys.sleep(20)
        data.frame(pid = Sys.getpid(),
                   node = Sys.info()[["nodename"]],
                   ncoresa = cores,
                   ncoresb = availableCores(),
                   stringsAsFactors = F)
      }
    }
    Reduce(rbind, dat_t)
  }
})

dat_all <- value(dat_f)
```
What is happening is that executing the `dat_t <- future(...)` lines starts a job on the cluster. This is running fine and without problems, however the last line `dat_all <- value(dat_f)` does not return the results, i.e. `dat_all` is an environment object. When I start an R session on the cluster and load the results of the job with `batchtools::loadRegistry()` and `batchtools::loadResult()` everything is as expected and from the runtime of the job I am certain that the 8 processes were running in parallel.

Running the {batchtools_slurm} -> {multicore} futures within an R session directly on the remote cluster works fine.

Note that when I run from my local machine only two nested futures, i.e.
```
plan(list(tweak(remote, workers = "myaccount@remote.cluster"),
          tweak(batchtools_slurm, resources = list(walltime = 600))
))

dat_f <- future({
    dat_t <- listenv()
    cores <- availableCores()
    for(f in 1:8) {
      dat_t[[f]] %<-% {
        Sys.sleep(20)
        data.frame(pid = Sys.getpid(),
                   node = Sys.info()[["nodename"]],
                   ncoresa = cores,
                   ncoresb = availableCores(),
                   stringsAsFactors = F)
      }
    }
    Reduce(rbind, dat_t)
})
dat_all <- value(dat_f)
```
everything works as expected, i.e. there are 8 jobs created running on the cluster and `dat_all` contains the expected `data.frame`.

Do you have any ideas why the results of the multicore future are not correctly distributed to my local machine?

**Comment by HenrikBengtsson** [comment]
You need to resolve the inner future.  That is, instead of doing:
```r
a %<-% { b %<-% { 42 } }
```
which returns the _future_ object behind `b`, do:
```r
a %<-% { b %<-% { 42 }; b }
```

Using `future()` and `value()`, the analogue is that you're currently doing:
```r
fa <- future({ fb <- future({ 42 }) })
```
which returns a future (`fb`), i.e. the value of the outer future that is assigned to `fb` will be future `fb`.  By doing:
```r
fa <- future({ fb <- future({ 42 }); value(fb) })
a <- value(fa)
```
you will get the value of the future expression for `fb`.

**Comment by tpilz** [comment]
Ah, indeed I forgot to resolve the first inner future and didn't notice. Now it works fine. Thanks!

**Comment by HenrikBengtsson** [comment]
Great
