### ISSUE TITLE
Cannot get toy example to work, could you kindly guide me for config ?

### ISSUE THREAD

**Issue by statquant** [HenrikBengtsson/future.batchtools#41]
Hello, I am trying to work a toy example using slurm
```
plan(batchtools_slurm, template = system.file("templates", "slurm-simple.tmpl", package = "batchtools"))
x %<-% { Sys.sleep(5); 3.14 }
```
`Error: Fatal error occurred: 101. Command 'sbatch' produced exit code 1. Output: 'sbatch: error: Invalid numeric value "" for cpus-per-task.'
`
I am probably missing something obvious, is there a document that could guide me to make this toy example work ?

**Comment by HenrikBengtsson** [comment]
Hi.  I don't have access to Slurm myself, so I cannot test it, but try with:

```r
library(future.batchtools)
plan(
  batchtools_slurm,
  template = system.file("templates", "slurm-simple.tmpl", package = "batchtools"),
  resources = list(ncpus = 2L, memory = "4G", walltime = 0)
)
```
for Slurm jobs requesting 2 tasks ("cores"), 4 GiB of RAM, and no time limit.

FYI, I just posted https://github.com/mllg/batchtools/issues/228 with a suggestion how that 'batchtools' package template could provide a bit more informative error messages when a resource parameter is missing like here.

**Comment by statquant** [comment]
Thank you it worked, for some reason `walltime` needed to be > 0 or the task would be pending forever.

**Comment by HenrikBengtsson** [comment]
Good to hear.

Yes, each system is configured slightly different, do in your case a zero walltime is not allowed
