### ISSUE TITLE
Loading back results from workers to the master process

### ISSUE THREAD

**Issue by statquant** [HenrikBengtsson/future.batchtools#43]
Hello @HenrikBengtsson when I use the slurm backend and generate tables (data.frame) as a result I have the impression that getting back the results is very slow and that this is due to how data is "ingested" back to the master process. By looking at the .future dir ectory I see .RDS files which might be a reason.

**If I am not totally wrong:**

In case of data.frame I think reading/writing `fst` files would give us at least a order of magnitude speed up.
- would you consider using fst in cases of data.frame outputs ?
- if yes would you point me to the code and I'll try to write a pull request

**Comment by HenrikBengtsson** [comment]
Hi. Since future.batchtools is just a thin Future API on top of the [batchtools](https://github.com/mllg/batchtools/) package, which handles all these things, please head over there for this feature request.
