### ISSUE TITLE
singularity support?

### ISSUE THREAD

**Issue by kkmann** [HenrikBengtsson/future.batchtools#44]
I was just wondering whether there are any plans to support running jobs within singularity containers? 
My HPC experience is limited (slurm only) but if I am not completely off, one would only have to modify the sbatch command slightly, right? Would that go in the template file?

**Comment by HenrikBengtsson** [comment]
Yes, controlling which Rscript binary to run would be set in the batchtools template file.  So, replace
```sh
## Launch R and evaluated the batchtools R job
Rscript -e 'batchtools::doJobCollection("<%= uri %>")'
```
with something like
```sh
## Launch R and evaluated the batchtools R job
singularity exec rocker_r-base.img Rscript -e 'batchtools::doJobCollection("<%= uri %>")'
```
where the image was built using something like:
```sh
$ singularity build rocker_r-base.img docker://rocker/r-base
```
