### ISSUE TITLE
Compatibility with promises package

### ISSUE THREAD

**Issue by michaelmayer2** [HenrikBengtsson/future.batchtools#80]
**Describe the bug**
When used with promises package, future.batchtools complains about a missing option "background" to `nbrOfWorkers()` and secondly about a missing function `nbrOfFreeWorkers()`

**Error Message**
`Unhandled promise error: nbrOfFreeWorkers() is not implemented for this type of future backend (please contacts the maintainer of that backend): ‘FutureStrategy’, ‘tweaked’, ‘batchtools_slurm’, ‘batchtools_template’, ‘batchtools’, ‘multiprocess’, ‘future’, ‘function’`

**Expected behavior**
No error displayed

When using the attached patch against latest future.batchtools from github fixes the issue. 

I am not sure if my approach of duplicating `nbrOfWorkers()` and renaming it to `nbrOfWorkers()`, additionally adding `background` as a dummy argument to both is sensible, at least the `promises` integration is working with this patch (see below). 

[promises-compat.diff.txt](https://github.com/HenrikBengtsson/future.batchtools/files/7914405/promises-compat.diff.txt)

**Comment by HenrikBengtsson** [comment]
Thanks for this, and sorry for the long delay. I think I finally got `nbrOfFreeWorkers()` implemented (Issue #67).  It's available in the develop branch.

**Comment by HenrikBengtsson** [comment]
**future.batchtools** 0.11.0 fixing this is now on CRAN.
